### PR TITLE
Add GE scanner physiological file functionality

### PR DESCRIPTION
**Pull request by nw-duncan**
Functionality to read and process GE scanner physiological recording files is added to the tool. 

Users can enter a single scanner generated file (with the name given to it by the scanner). Note that these do not have any suffix. If there are other files corresponding to other measurement modalities (i.e., PPG, respiration belt, or EKG) then these will be found automatically and added. 

## Proposed Changes
  - New function to check if an input file has the filename convention of a GE file. If so all other relevant files are found and a ".gep" suffix appended to each (preserving the processing pipeline implemented for other supported file types)
  - New function to read in the relevant files. This also adds a simulated trigger channel as GE scanners do not, to my knowledge, output such information natively 
  - All other steps proceed as with currently supported files

## Change Type

- [ ] `bugfix` (+0.0.1)
- [x] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `Internal`
- [ ] `Testing`

## Checklist before review
- [x] I added everything I wanted to add to this PR.
- [x] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [x] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [x] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by smoia** [comment]
@nw-duncan once #430 is tested and merged, could you rebase this PR on the new master? I switched back CI to Circle CI, so we can exclude missed runs due to CI providers.

**Review by smoia — APPROVED** [review]
LGTM!

**Comment by smoia** [comment]
@nw-duncan if you agree, we merge this part in now, and we wait for documentation later?

**Comment by nw-duncan** [comment]
Yes, let's do that.

**Comment by smoia** [comment]
:rocket: PR was released in [`2.8.0`](https://github.com/physiopy/phys2bids/releases/tag/2.8.0) :rocket:

**Pull request merged**
