### PR TITLE
Fix linting errors

### LINKED ISSUE #293: There are linting error that need to be addressed
## Possible solution

Go one by one and fix them!

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #293

## Proposed Changes

  - Fix linting errors around the entire package.

### CODE REVIEW

**Comment by vinferrer** [comment]
where are the other tests?

**Comment by eurunuela** [comment]
> where are the other tests?

I think CircleCI went a bit crazy with so many consecutive commits. They should start appearing now that I've canceled the tests on previous commits.

**Comment by eurunuela** [comment]
Style check passed! Yay! 🎉

**Comment by vinferrer** [comment]
LGTM!!!!

**Review by vinferrer — APPROVED** [review]

**Comment by tsalo** [comment]
@eurunuela Have you been cancelling old builds manually?

To do it automatically, on the `phys2bids` CircleCI page, go to **Project Settings** --> **Advanced** --> turn on **Auto-cancel Redundant Builds**

**Comment by eurunuela** [comment]
Thank you so much @tsalo ! That will make silly PRs like this one even smoother.

**Pull request merged**
