### PR TITLE
Update all-contributors

### PR DESCRIPTION
**Pull request by smoia**
Closes none

## Proposed Changes

  -Updated all-contributors.

@RayStick @tsalo can you check this?
@physiopy/all any other contribution missing?

### CODE REVIEW

**Comment by RayStick** [comment]
LGTM

**Comment by RayStick** [comment]
Do you want me to review it?

**Comment by smoia** [comment]
@RayStick no, no worries! If @tsalo is also ok with it, I'm going to merge it with my [super cow powers](https://unix.stackexchange.com/questions/92185/whats-the-story-behind-super-cow-powers).

**Comment by RayStick** [comment]
Okay, sure!
(I would like to know more about your super cow powers).

**Pull request merged**
