### PR TITLE
Migrate testing to Cirrus CI

### LINKED ISSUE #373: Circle CI Credits
As you may have notice last week we used all the free credits in our Circle CI plan, and this wee we are on the same track with much less PRs:
image

This sudden change is due mainly because we started using the windows build in Circle ci for the windows testing. Here you have some info on how many credits/min a job costs:
image

Yes 40 credits/min for windows VM. So there would be two options to discuss

## Outstanding questions

    - Return to azure Pipelines
    - Apply for circle CI open source credits program: https://circleci.com/open-source/  400.000 credits per month

I would go for the second option to see if the open source credits are valid for Windows builds, if they are not, since we are increasing our jobs for different python versions test it would be still nice to have free credits. 
According to the wiki:
```
Open source credit usage
Organizations on our free plan get 400,000 free credits per month for Linux open source builds. Using our free plan and keeping your repository public will enable this for you.

If you build on macOS, we also offer organizations on our free plan 25,000 free credits per month to use on macOS open source builds. For access to this, contact our team at billing@circleci.com.
```
Maybe they are gonna do the same for windows instead of Mac, I think it's worth and email

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #373 
Closes #354 
Closes #353  

## Proposed Changes

  - Adapts all the tests from ``Circle CI`` to ``Cirrus CI``
  - Implements the matrix configuration to ``makeenv``, ``unittest`` and ``integration`` tasks to simplify the code.
  -  This CI uses the ``codecov bash uploader``. Reading the docs in ``codecov`` I realized the merging of the reports is done automatically, no need for the ``merge_coverage``  job. 
  -  Adds python 3.8 and 3.9 tests
  - ``Cirrus CI`` has no credits charge for open source projects, this includes ``windows``, ``macOS`` and ``linux`` jobs.

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [x] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [ ] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by vinferrer** [comment]
We need someone to activate Cirrus-CI for physiopy

**Comment by vinferrer** [comment]
https://github.com/marketplace/cirrus-ci

**Comment by eurunuela** [comment]
I see you managed to make the matrix with python versions work, this is great!

If you think the PR is ready for review, please click on the `Ready for review` button.

**Comment by vinferrer** [comment]
I have updated the description above with all the changes

**Comment by vinferrer** [comment]
> If you think the PR is ready for review, please click on the `Ready for review` button.

Maybe we should wait for the next Thursday so we take the decision to change with the others

**Comment by smoia** [comment]
@vinferrer could you remove the circleci makeenv_37 configuration to see if codecov gets the Cirrus CI run results (and also so that rerunning we can check if the credits are not used - at the moment we have 60 credits)?

**Comment by vinferrer** [comment]
> @vinferrer could you remove the circleci makeenv_37 configuration to see if codecov gets the Cirrus CI run results (and also so that rerunning we can check if the credits are not used - at the moment we have 60 credits)?

Codecov is getting the cirrus-ci results, I checked that because i deleted all the tests and only upload the cirrus unittest results and the coverage dropped, then i uploaded both unittest and integration and it got back to the normal value. The makeenv_37 is there because it was the only way i manage to avoid the build error from circle CI.

**Comment by eurunuela** [comment]
What build error from CircleCI? If we decide to use CirrusCI, we should just delete the `.circleci` folder.

**Comment by vinferrer** [comment]
I know but look

**Comment by vinferrer** [comment]
This error

**Comment by eurunuela** [comment]
I see now. This we will have to fix from the CircleCI website if/when we decide to go with CirrusCI.

Right now, CircleCI expects a configuration file that does not exist, hence the error saying `No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.`

Simply unlinking CircleCI from this repo should be enough to fix the error.

**Comment by vinferrer** [comment]
I know but that implied deciding to do the change so i wanted to try first

**Comment by vinferrer** [comment]
> @vinferrer could you remove the circleci makeenv_37 configuration to see if codecov gets the Cirrus CI run results (and also so that rerunning we can check if the credits are not used - at the moment we have 60 credits)?

About the credits, I cite directly:
Every organization on GitHub gets 60 compute credits upon Cirrus CI App installation. It has never been easier to try Cirrus CI on private organizational repositories.

**Comment by smoia** [comment]
I'm personally ok with this change, given that is a good solution that @vinferrer put together to solve many problems at once.
@tsalo , @62442katieb , and @physiopy/phys2bids, do you have anything against it?

**Review by eurunuela — APPROVED** [review]
Changes look great to me. Thank you @vinferrer !

**Comment by 62442katieb** [comment]
Looks good to me, too! Thanks for working on this @vinferrer !

**Review by 62442katieb — APPROVED** [review]

**Comment by vinferrer** [comment]
Please let's not merge until stefano deactivates circle CI

**Comment by smoia** [comment]
@vinferrer what do I have to do? Is unsubscribing CircleCI enough?

(PS: please then pass this setting over to `phys2denoise` and `peakdet`.

**Comment by smoia** [comment]
Ok, I unfollowed the project in CircleCI, and denied its access. It should be enough?

**Review by tsalo — APPROVED** [review]

**Comment by vinferrer** [comment]
Yup, no circle ci test

**Comment by vinferrer** [comment]
By the way we should put that we do support python3.8 and 3.9 now

**Comment by vinferrer** [comment]
@smoia this is ready for approval

**Comment by smoia** [comment]
Approved and merged!

**Comment by smoia** [comment]
Please open the same PR for `phys2denoise` though!
@62442katieb and @rmarkello , would you have anything against adopting CirrusCI for `peakdet`?

**Comment by vinferrer** [comment]
Okay but let me rest

**Comment by 62442katieb** [comment]
> Please open the same PR for `phys2denoise` though!
> @62442katieb and @rmarkello , would you have anything against adopting CirrusCI for `peakdet`?

Nothing at all, go ahead!

**Comment by rmarkello** [comment]
Agreed, that's totally fine 👍💯

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Pull request merged**
