### PR TITLE
Add BIDS_VALIDATOR test

### LINKED ISSUE #355: Add test to pass a BIDS validator
## Detailed Description

I run a BIDS validator on a dataset that I BIDSified with an older version of phys2bids. Fun fact, after a while that the validator worked out fine, now it returns an error on the (old) way to express frequencies.
I realised that we are not testing whether we make output BIDS compatible or not - I know we are, but it is risky. We should check it AT LEAST on one output.
We can use this [BIDS validator](https://github.com/bids-standard/bids-validator) and build a test that we run with the others.

Question for @vinferrer (cause I think you worked on it during HBMH2020 and you recently worked on I/O): do we always transform the sampling frequency into Hz? 

## Context / Motivation

Just to be sure that what we output when we want a BIDS format is 100% BIDS compatible.
Besides, if there's any change in the BIDS spec about physiological files, we need to know it and update phys2bids! 

## Possible Implementation

- Check [this repo](https://github.com/bids-standard/bids-validator) and its docker implementation
- Build a test for CircleCI or a GitHub action that, either cloning the repo or building the docker, runs phys2bids with heuristic rules on a test file and then runs the validator on the output.
- PS: It might not be python based?
- PPS: We need to understand how to return an error when we don't pass the validator
- PPPS: We might have to implement a lot of "ignore errors" and "ignore warnings" to actually pass the test
- PPPPS (and last): maybe some friends from the BIDS team and/or the BIDS validator team can help us setting this up.

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #355 

This addition to the config file sets a test that runs bids_validator on the tutorial file 

## Proposed Changes

  - add tests for bids_validator
  -
  -

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [x] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [ ] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by vinferrer** [comment]
Okay, I think this is working, l am gonna leave it as a draft until the PR mentioned in this issue: https://neurostars.org/t/quick-validation-failed-on-physiological-files/17611/6 gets approved and a new release is passed. However as you can see it is doing exactly what we want. Now that the bids-validator doesn't accept physiological only bids dataset it gives an error and breaks the test.

**Comment by vinferrer** [comment]
@eurunuela How do you use the makeenv_37 enviroment work in your others jobs, I tried to recreate the steps but since i couldn't i reisntall phys2bids in my bids_validate job

**Comment by eurunuela** [comment]
> @eurunuela How do you use the makeenv_37 enviroment work in your others jobs? I tried to recreate the steps but since i couldn't i reisntall phys2bids in my bids_validate job

I think you're missing this:

```yml
- bids_validate
    requires:
      - makeenv_37
```

**Review by eurunuela — CHANGES_REQUESTED** [review]
LGTM! Thank you @vinferrer . I set it as "request changes" until the test passes. Then I'll approve.

Edit: I forgot to mention that if you think this is ready for review, you should click on the button 😉

**Comment by vinferrer** [comment]
> LGTM! Thank you @vinferrer . I set it as "request changes" until the test passes. Then I'll approve.
> 
> Edit: I forgot to mention that if you think this is ready for review, you should click on the button 😉

No, it's not ready, we have to wait for the bids-validator update that accepts only physiological datasets

**Comment by vinferrer** [comment]
I think bids-validator people are not gonna allow only ``physio`` datasets, So I decided to put a dummy file

**Review by smoia — APPROVED** [review]
LGTM!

**Review by eurunuela — APPROVED** [review]
This is super useful. Thank you @vinferrer !

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.2`](https://github.com/physiopy/phys2bids/releases/tag/2.3.2) :rocket:

**Pull request merged**
