### PR TITLE
Add .mailmap to improve `git shortlog -sn` output

### PR DESCRIPTION
**Pull request by yarikoptic**
.mailmap is mechanism to properly account for contributors using different git configuration "ids".  

<details>
<summary>output on master master</summary> 

```shell
$> git shortlog -sn | nl
     1	   446	Stefano Moia
     2	   415	vinferrer
     3	   231	Vicente Ferrer
     4	   215	smoia
     5	   112	François Lespinasse
     6	   101	Eneko
     7	    74	Eneko Uruñuela
     8	    74	eurunuela
     9	    54	Ross Markello
    10	    49	Rachael Stickland
    11	    44	allcontributors[bot]
    12	    19	Apoorva Ayyagari
    13	     6	Taylor Salo
    14	     4	Daniel Alcalá
    15	     4	Merel van der Thiel
    16	     4	Vittorio Iacovella
    17	     3	RayStick
    18	     3	kristinazvolanek
    19	     2	BrightMG
    20	     2	Inés Chavarría
    21	     2	Molly Bright
    22	     1	Daniel Alcalá López
    23	     1	Katie Bottenhorn
    24	     1	Kristina Zvolanek
    25	     1	Victor
    26	     1	vferrer
```
</details>

<details>
<summary>output on this PR</summary> 

```shell
$> git shortlog -sn | nl                                                    
     1	   661	Stefano Moia
     2	   647	Vicente Ferrer
     3	   249	Eneko Uruñuela
     4	   112	François Lespinasse
     5	    54	Ross Markello
     6	    49	Rachael Stickland
     7	    44	allcontributors[bot]
     8	    19	Apoorva Ayyagari
     9	     6	Taylor Salo
    10	     4	Daniel Alcalá
    11	     4	Kristina Zvolanek
    12	     4	Merel van der Thiel
    13	     4	Vittorio Iacovella
    14	     3	RayStick
    15	     2	BrightMG
    16	     2	Inés Chavarría
    17	     2	Molly Bright
    18	     1	Daniel Alcalá López
    19	     1	Katie Bottenhorn
    20	     1	Victor
    21	     1	Yaroslav Halchenko
```
</details>

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [x] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by smoia** [comment]
Hello @yarikoptic ! Thank you for the proposal!

I don't think there's a major issue in adding .mailmap. Do you have any specific use in mind though?

**Review by smoia — CHANGES_REQUESTED** [review]
Looks completely fine to me, could I ask you to add @danalclop to this list before merging? I noticed that in the shortlog of this PR he appears both as Daniel Alcala' and as Daniel Alcala' Lopez

**Comment by yarikoptic** [comment]
> I don't think there's a major issue in adding .mailmap. Do you have any specific use in mind though?

`git shortlog -sn` is my immediate use case

**Comment by yarikoptic** [comment]
> both as Daniel Alcala' and as Daniel Alcala' Lopez

added, force-pushed

**Review by smoia — APPROVED** [review]
LGTM!

And I think I can merge it in without waiting for a second review

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.3`](https://github.com/physiopy/phys2bids/releases/tag/2.3.3) :rocket:

**Pull request merged**
