### PR TITLE
Rename function `utils.writefile` to `utils.write_file` to respect style

### LINKED ISSUE #332: Rename utils.writefile() to utils.write_file()
## Summary

Most of the functions in `phys2bids.utils` are in PEP8-compatible snake case, but [`phys2bids.utils.writefile()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L212) is not. We can rename it to `write_file()` to match convention.

## Next Steps

    * Rename the function
    * Update tests
    * Update all uses of the function throughout the package
    * Update the API page of the docs

### PR DESCRIPTION
**Pull request by ineschh**
Closes #332 

## Proposed Changes

  - Rename the function
  - Update tests
  - Update all uses of the function throughout the package

Didn't update the API page of docs since apparently there isn't one for utils

### CODE REVIEW

**Review by smoia — APPROVED** [review]
LGTM!

**Comment by smoia** [comment]
@eurunuela wanna have a look?

**Review by eurunuela — APPROVED** [review]
LGTM!

**Comment by eurunuela** [comment]
🔔

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:

**Pull request merged**
