### PR TITLE
Rename utils.writejson() to utils.write_json()

### LINKED ISSUE #333: Rename utils.writejson() to utils.write_json()
## Summary

Most of the functions in `phys2bids.utils` are in PEP8-compatible snake case, but [`phys2bids.utils.writejson()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L238) is not. We can rename it to `write_json()` to match convention.

## Next Steps

    * Rename the function
    * Update tests
    * Update all uses of the function throughout the package
    * Update the API page of the docs

### PR DESCRIPTION
**Pull request by merelvdthiel**
Closes #333 

## Proposed Changes

  -Rename the function
  -Update tests
  -Update all uses of the function throughout the package

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `internal` (no version update)
- [ ] `documentation` (no version update)

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [x] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [x] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Review by 62442katieb — APPROVED** [review]
this is also legit! 🥳

**Review by eurunuela — APPROVED** [review]
Looks great! Thank you @merelvdthiel 😊

**Comment by eurunuela** [comment]
Would you like to do the honors and merge it yourself @merelvdthiel ?

**Comment by smoia** [comment]
@eurunuela she can't :rofl:

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:

**Pull request merged**
