### PR TITLE
Fix call to conda environment reference in the test configuration file

### PR DESCRIPTION
**Pull request by eurunuela**
Closes none.

I found a tiny error in our testing configuration file. We were referencing a conda environment that did not exist. Good thing we created our own when that one didn't exist.

## Proposed Changes

  - Correctly check if our conda environment has already been created.

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [x] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Review by vinferrer — APPROVED** [review]
LGTM!!

**Comment by eurunuela** [comment]
> LGTM!!

Thank you @vinferrer . Given that it's a bug fix, you can merge it if you're happy with the change.

**Comment by smoia** [comment]
Wait, let me fix a couple of things first

**Comment by eurunuela** [comment]
> Remember that `BugFIX` will trigger a new release (0.0.+1).
> 
> Here you're not modifying code, but tests - even if it is a "bug fix" in a general sense, you're not implementing anything that has to be released.

My bad. I was actually thinking of only adding the testing label when I wrote. Apparently I did the opposite 🤣 Thank you @smoia !

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.2`](https://github.com/physiopy/phys2bids/releases/tag/2.3.2) :rocket:

**Pull request merged**
