### PR TITLE
Adds integration tests

### LINKED ISSUE #130: Automatic testing on data with Travis
I believe we should have some automatic testing on data with Travis before we release our first non-beta version. This issue is related to #9.

## Context / Motivation

We should always make sure the code works on data, as it is the main purpose of the project. It would definitely make testing the code easier. It could even be helpful for the tutorials in our documentation.

## Possible Implementation

This feature should be implemented in a similar fashion to the unit tests.

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #130 
## Proposed Changes

  - adds integration test to txt file
  -
  -

### CODE REVIEW

**Comment by vinferrer** [comment]
This was unexpected, i thing the coverage increased that much because I am executing from the console to call the parser and therefore all phys2bids gets called

**Comment by vinferrer** [comment]
OMG, this was unexpected. I think the coverage improves that much because i am running the phy2bids from the console and therefore all the suite gets executed

**Comment by smoia** [comment]
That was expected, actually - and it was what we discussed in #130 and #144 (and was assigned to @eurunuela - please don't step on each others' feet!).
Link those issues and this PR, if you're making this become an integration or a function test - in which case, you need to add assertions on the outputs.
Also, testing cli/run.py doesn't necessarily mean we need to run the whole program.

**Comment by vinferrer** [comment]
We decided to convert this PR in the integration test PR

**Comment by vinferrer** [comment]
By the way, maybe we should separate these integration test in Travis from the normal unit test

**Comment by eurunuela** [comment]
This is being taken care of by #166

**Pull request closed without merging**
