### PR TITLE
correct chtrig check in phys2bids main workflow

### LINKED ISSUE #389: phys2bids not working with chtrig=0
While  working on automatic channel detection I came across the following problem.
## Expected Behavior

When chtrig is set to 0 or no value is entered by the user phys2bids should run anyway and try to detect the trigger automatically.
## Actual Behavior

What happens in phys2bids.py:

By default chtrig is set to 0 
image

however in line 195 an exception is raised when chtrig < 1
image

so the workflow crashes
image

## Steps to Reproduce the Problem

    1.run phys2bids without entering chtrig or setting chtrig to 0

## Specifications

    - Python version: 3.9
    - phys2bids version: 2.4.0
    - Platform: Ubuntu 20.04.2 LTS

## Possible solution

I guess this could be easily fixed by removing the chtrig<1 check in line 195

### PR DESCRIPTION
**Pull request by drombas**
Closes #389 

## Proposed Changes

  - Change chtrig check value from 1 to 0 (phys2bids.py)
  - Modify chtrig test to check that a negative value raises the exception (test_phys2bids.py)
 
## Change Type

- [x] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [x] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [x] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by drombas** [comment]
Hi! anything preventing merging this?

**Review by smoia — APPROVED** [review]
LGTM!

**Review by smoia — APPROVED** [review]
LGTM!

**Comment by smoia** [comment]
:rocket: PR was released in [`2.4.1`](https://github.com/physiopy/phys2bids/releases/tag/2.4.1) :rocket:

**Pull request merged**
