### PR TITLE
Create folder code/conversion to store trigger and channel plots, yaml and heuristic files and the call.sh file

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #256 

## Proposed Changes

  - Create  ``code/coversion`` folder
  - generating log, trigger_plot, channel_plot, heuristic file and yam file to ``code/coversion`` folder
  - create new file ``call.sh`` that contains the original call to phys2bids

### CODE REVIEW

**Comment by eurunuela** [comment]
If the tests pass, this should be ready @vinferrer @smoia

**Comment by vinferrer** [comment]
It says that there is coverage dropout

**Comment by eurunuela** [comment]
That's weird. The report inside codevoc shows an increase in coverage...

**Comment by eurunuela** [comment]
I can add a test to check that the file is generated in the integration tests.

**Comment by vinferrer** [comment]
please do

**Comment by eurunuela** [comment]
Done!

**Comment by vinferrer** [comment]
@smoia  had death by brainhack

**Pull request merged**
