### PR TITLE
Make sure we delete testing files after finishing tests

### LINKED ISSUE #304: Tests output files are not deleted
Some files are not deleted once tests are finished.

## Expected Behavior
Tests should not leave any files or folders.

## Steps to Reproduce the Problem

image

## Specifications
    - Python version: Python 3.6.9
    - phys2bids version: phys2bids v1.3.0-beta+1033.gc02826e
    - Platform: Ubuntu

## Possible solution
This is probably caused by the ``test_integration.py``

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #304 

## Proposed Changes

  - Now when running pytest locally all the files are generated in temporal dirs
  -
  -

### CODE REVIEW

**Comment by vinferrer** [comment]
@eurunuela  Could you review this?

**Comment by eurunuela** [comment]
Of course, I'll find some time today to review this

**Comment by eurunuela** [comment]
@vinferrer thank you for the PR. 

I see you only worked on two of the testing python files. Are these two the only ones generating files that don't get removed?

I'm asking cause you probably know about it better than I do.

**Comment by vinferrer** [comment]
I just executed pytest after merging a master and no files are generated in the repo

**Review by eurunuela — APPROVED** [review]
LGTM then!

**Comment by vinferrer** [comment]
This is a bug fix, we only need one reviewer

**Comment by smoia** [comment]
:rocket: PR was released in [`2.2.1`](https://github.com/physiopy/phys2bids/releases/tag/2.2.1) :rocket:

**Pull request merged**
