### PR TITLE
Add support for Spike2 files

### PR DESCRIPTION
**Pull request by htwangtw**
Addresses #405.

The current implementation uses the official API, `sonpy`, from CED. `sonpy` is closed sourced.
**In order to support `sonpy`, the minimal python version should be 3.7.** Hence I will mark this as part of the major release.

The scanner volume trigger in the test file was stored as a "marker" channel. The `sonpy` API returns time points of markers, rather than a timeseries. The module I wrote has been tested locally. I cannot run the full test due to bandwidth and data limit. Will check if this breaks other tests.

## Proposed Changes

  - Add `phys2bids.io.load_smr`

## Change Type

- [ ] `bugfix` (+0.0.1)
- [x] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [x] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [x] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by htwangtw** [comment]
Looks like conda doesn't support the latest version of sonpy - I am not familiar with Cirrus CI, if anyone can look into how to get pip to install certain libraries, that would be grand.

**Review by smoia — APPROVED** [review]
LGTM (let's wait for the tests)!

**Comment by htwangtw** [comment]
hmmm all python 3.6 checks failed. Looks like a sonpy problem - they use the versioning numbers in a very special way (1.6.x -> python 3.6 support; 1.7.x -> python 3.7 etc)

**Comment by smoia** [comment]
More than that, I believe that sonpy only supports python 3.7 and above (If I read it
Python 3.6 reaches its EOL in a month, so I see two options here:
- we add an exception to not run this test when running python 3.6, or
- we can speed up things and end support for python 3.6 earlier on, removing its tests alltogether.

WDYT?

**Comment by htwangtw** [comment]
Ah good to know! 
I would prefer 
1. explicitly exclude 3.6 for sonpy related functions
2. end support for 3.6 in future iteration. 

Dealing with deprecation and adding a new function in one PR might be too much

**Comment by smoia** [comment]
Agreed! Let's exclude 3.6 testing for sonpy.
Do you need help with it?

**Comment by htwangtw** [comment]
I will have a look and likely working on this next week

**Comment by smoia** [comment]
@htwangtw I tried to update this PR to merge it in.
At the moment, I still cannot figure out how to fix the installation of sonpy - mainly due to the fact that python 3.10 cannot install it.

As a temporary solution, I marked as xfail the sonpy test. I don't love this, but I don't know how to solve it at the moment.

If you agree with the changes, we merge!

**Comment by smoia** [comment]
:rocket: PR was released in [`2.9.0`](https://github.com/physiopy/phys2bids/releases/tag/2.9.0) :rocket:

**Pull request merged**
