### PR TITLE
Replace utils.path_exists_or_make_it() with os.makedirs()

### LINKED ISSUE #334: Replace utils.path_exists_or_make_it() with os.makedirs()
## Summary

The function [`phys2bids.utils.path_exists_or_make_it()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L113) can be replaced with [`os.makedirs(exist_ok=True)`](https://docs.python.org/3/library/os.html#os.makedirs). It also doesn't require the `if` statement that's used to check if the path already exists.

## Next Steps

    * Remove the function and associated tests
    * Remove the item from the API docs page
    * Replace the function call throughout the package

### PR DESCRIPTION
**Pull request by merelvdthiel**
Closes #334 

## Proposed Changes

  -Remove the function and the associated tests
  -Replace the function call throughout the package

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `internal` (no version update)
- [ ] `documentation` (no version update)

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [x] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [x] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Review by 62442katieb — APPROVED** [review]
is legit, can confirm.

**Comment by smoia** [comment]
Looks legit. @62442katieb want to do the honours of merging?

**Comment by 62442katieb** [comment]
> Looks legit. @62442katieb want to do the honours of merging?

I would _sincerely_ be honored.

**Comment by smoia** [comment]
:rocket: PR was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:

**Pull request merged**
