### PR TITLE
Clarify installation instructions and tutorial

### LINKED ISSUE #210: Suggestion for installation instructions and phys2bids tutorial
##  Summary
After working through the phys2bids tutorial:
A suggestion for the installation instructions in installation.srt document.
A suggestion for the howto.srt document.

## Next Steps

    * In installation instructions: clarify what the difference is between installing as a package and cloning from the git repo. Make a clearer distinction in the installation steps for these two options. (e.g. if you use "pip3 install phys2bids" is that all you need to do before checking the version and using phys2bids?)
    * In phys2bids tutorial: add summary list of all options that can be used after the phys2bids command and what their purpose is (basically, a more detailed version of the help text). For simplicity, instructions on how to use the -h option could be added.

### PR DESCRIPTION
**Pull request by drombas**
Closes  #210 

Small clarification of the documentation.

## Proposed Changes

installation.rst
  - Clarify the difference between installation with and without pip
  - Clarify the installation steps
  - Correct setup.py installation command

howto.rst
  - Add phys2bids -h description as well as a link to the command line usage page.

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [x] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [x] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Review by smoia — COMMENTED** [review]
Hello @drombas!

Thank you for the PR! This LGTM!

@RayStick or others, do you want to have a look at it?

**Review by vinferrer — APPROVED** [review]
LGTM too

**Comment by vinferrer** [comment]
Thought we should wait for others to merge this PR

**Comment by smoia** [comment]
:rocket: PR was released in [`2.4.1`](https://github.com/physiopy/phys2bids/releases/tag/2.4.1) :rocket:

**Pull request merged**
