### PR TITLE
Stop reordering trigger

### PR DESCRIPTION
**Pull request by smoia**
Closes nothing
Addresses #118 and possibly #148 .

## Proposed Changes

  - Trigger isn't moved any more to channel 1, instead it's kept where it should be.

### CODE REVIEW

**Comment by vinferrer** [comment]
Should we address this also for txt files here

**Comment by vinferrer** [comment]
I can tell you the needed changes, it should be only a few lines

**Comment by smoia** [comment]
Let's work on this together, possibly we'll need to merge #148 with this?

**Comment by smoia** [comment]
I don't know if this should be a refactoring and majormod PR, or a BugFIX PR. I added all the labels in case, but let me know what you think and remove the label(s) that are not necessary.

I checked the drop in testing, and it's due to the fact that `physio_obj.py` and `phys2bids.py` are not tested yet. I would pass them through integration tests, but if not, I'll open a new issue for tests (and eventually a PR).

**Pull request merged**
